[build]
command = "cd exampleSite && mise install && mise run install-example-deps && hugo --gc --minify"
publish = "exampleSite/public"

[build.environment]
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "cd exampleSite && mise install && mise run install-example-deps && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "cd exampleSite && mise install && mise run install-example-deps && hugo --gc --minify -b $DEPLOY_PRIME_URL"
